name: Testes do Back-end Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4

    - name: 2. Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 3. Instalar as dependências
      run: |
        python -m pip install --upgrade pip
        # Como a raiz é 'back', o ficheiro está no caminho direto
        pip install -r back/requirements.txt
    
    - name: 4. Executar os testes
      run: |
        # Como a raiz é 'back', o pytest encontrará a pasta 'tests' automaticamente
        pytest -v
      env:
        # Os secrets continuam a ser passados da mesma forma
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        # ... e as outras variáveis, se necessário